; PlatformIO Project Configuration File for CameraCommander Motor Firmware

[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 9600
upload_speed = 115200
lib_deps =
    waspinator/AccelStepper @ ^1.64

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
upload_speed = 921600
lib_deps =
    waspinator/AccelStepper @ ^1.64
